### ISSUE TITLE
Implement Search

### ISSUE THREAD

**Issue by lassiter** [lassiter/FamNet#9]
Reference #8 for scope.

Options are:
- to use [algoliasearch-rails](https://github.com/algolia/algoliasearch-rails) since react.js is already going to be used and allow deeply contextual searches with partials based on JSON.
- create database query search in rails that is simple, or complicated [thoughtbot full text search article](https://robots.thoughtbot.com/implementing-multi-table-full-text-search-with-postgres)
- to use something like Elasticsearch with an integration like the attached image.

![1_rz0tdq6miutuvzyinpfo0w 2x](https://user-images.githubusercontent.com/13928088/39460925-d926e5da-4ccc-11e8-9d1a-514390abb6ff.png)

The primary issue is should the user be able to search based on content, titles, or both?

**Comment by kishorenc** [comment]
@lassiter Stumbled on this issue and thought I should point you to [Typesense](https://github.com/typesense/typesense). Think of something as fast+simple as Algolia but opensource like Elasticsearch. Regardless of what you end up using, always happy to hear any feedback you might have!

**Comment by lassiter** [comment]
Hey @kishorenc, thanks for the suggestion. I'll check it out. I think for now, as a MVP, the search function will mainly just be some simple SQL queries. Once the alpha is released, it'll be easier to see the needs then.
